### PR TITLE
Milestone2 user interface

### PR DESCRIPTION
**Pull request by Ahmed-Benj**
Hello TSE,

Please review my milestone 2 of the project and approve it/comment if it lacks something.

Kind regards,
Ahmed

### CODE REVIEW

**Review by SajjadAhmad14 — CHANGES_REQUESTED** [review]
# Invalid Review Request

## Please make sure all Rubocop checks are passing before submitting the code review request. Moreover, the Pull request should have a meaningful summary of what you worked on in this milestone. Kindly request another code review once you are ready!

### Happy Coding!
## You can always connect with me on slack ( @Sajjad Ahmad ).

**Comment by Ahmed-Benj** [comment]
Hello,

I have corrected linter issues.

This pull request is to merge modifications made within milestone 2 of tic-tac-toe project into development branch and includes :

1. Requesting data from players
2. Displaying board
3. Displaying basic instructions and recommendations for players to start the game

Kind regards,
Ahmed

**Review by SajjadAhmad14 — CHANGES_REQUESTED** [review]
# Changes Required :recycle:
> "Change is inevitable. Change is constant. -Benjamin Disraeli"
## Hello, you have been doing a tremendous job so far :ok_hand:
## But there are some changes to make in order to get this milestone approved.
- [x] The default branch should be development. Please see [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/gitflow.png).
- [x] User name should not be empty. The user should be asked to enter a valid name If he tries to enter the game with an invalid name.
- [x] Game should inform the player if the selected move is invalid (without computing what an invalid move is). Please see [example](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/invalid_move.png).
- [x] game should display board after the player move (without computing which spots on the board are taken). Please see [example](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/player_turn.png).
- [x] Game should inform the player if the selected move is a winning move (without computing the winning move). Please see [example](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/game_win%2059.png).
- [x] Game should inform the player if the selected move is a draw move (without computing draw). Please see [example](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/game_tie.png).
- [x] Game repeats all actions for the next player's move. Please see [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/game_flow_example.gif).

### Happy Coding! 

## You can always connect with me on slack ( @Sajjad Ahmad ).

**Comment by Ahmed-Benj** [comment]
Hello,

I have fixed mentioned errors.
Could you please re-review my solution

Kind regards,

**Review by MkrtichSargsyan — APPROVED** [review]
## _Status:_ Approved  :hamster: :rocket:
Hi Guys.

Congratulations on your hard work, your project is now approved, 


You can go ahead and merge this branch to the base branch of this repo.

Good luck in your future projects and happy coding :relaxed:

> ps: . If you have any questions about my review or need help, you can message me on slack ( @mkrtichsargsyan )

**Pull request merged**
